/** 2018 IECC Table C301.1 / R301.1 — climate zone by county. * = warm-humid. */
export const COUNTY_RAW = `
AL
Autauga:3A,Baldwin:2A*,Barbour:2A*,Bibb:3A,Blount:3A,Bullock:2A*,Butler:2A*,Calhoun:3A,Chambers:3A,Cherokee:3A,Chilton:3A,Choctaw:2A*,Clarke:2A*,Clay:3A,Cleburne:3A,Coffee:2A*,Colbert:3A,Conecuh:2A*,Coosa:3A,Covington:2A*,Crenshaw:2A*,Cullman:3A,Dale:2A*,Dallas:2A*,DeKalb:3A,Elmore:3A,Escambia:2A*,Etowah:3A,Fayette:3A,Franklin:3A,Geneva:2A*,Greene:3A,Hale:3A,Henry:2A*,Houston:2A*,Jackson:3A,Jefferson:3A,Lamar:3A,Lauderdale:3A,Lawrence:3A,Lee:3A,Limestone:3A,Lowndes:2A*,Macon:2A*,Madison:3A,Marengo:2A*,Marion:3A,Marshall:3A,Mobile:2A*,Monroe:2A*,Montgomery:2A*,Morgan:3A,Perry:3A,Pickens:3A,Pike:2A*,Randolph:3A,Russell:2A*,Shelby:3A,St. Clair:3A,Sumter:3A,Talladega:3A,Tallapoosa:3A,Tuscaloosa:3A,Walker:3A,Washington:2A*,Wilcox:2A*,Winston:3A
AK
Aleutians East:7,Aleutians West:7,Anchorage:7,Bethel:8,Bristol Bay:7,Denali:8,Dillingham:7,Fairbanks North Star:8,Haines:7,Hoonah-Angoon:7,Juneau:7,Kenai Peninsula:7,Ketchikan Gateway:7,Kodiak Island:7,Kusilvak:8,Lake and Peninsula:7,Matanuska-Susitna:7,Nome:8,North Slope:8,Northwest Arctic:8,Petersburg:7,Prince of Wales-Hyder:7,Sitka:7,Skagway:7,Southeast Fairbanks:8,Valdez-Cordova:7,Wade Hampton:8,Wrangell:7,Yakutat:7,Yukon-Koyukuk:8
AZ
Apache:5B,Cochise:3B,Coconino:5B,Gila:4B,Graham:3B,Greenlee:4B,La Paz:2B,Maricopa:2B,Mohave:3B,Navajo:5B,Pima:2B,Pinal:2B,Santa Cruz:3B,Yavapai:4B,Yuma:2B
AR
Arkansas:3A,Ashley:3A,Baxter:4A,Benton:4A,Boone:4A,Bradley:3A,Calhoun:3A,Carroll:4A,Chicot:3A,Clark:3A,Clay:4A,Cleburne:3A,Cleveland:3A,Columbia:3A,Conway:3A,Craighead:3A,Crawford:3A,Crittenden:3A,Cross:3A,Dallas:3A,Desha:3A,Drew:3A,Faulkner:3A,Franklin:3A,Fulton:4A,Garland:3A,Grant:3A,Greene:3A,Hempstead:3A,Hot Spring:3A,Howard:3A,Independence:3A,Izard:4A,Jackson:3A,Jefferson:3A,Johnson:3A,Lafayette:3A,Lawrence:3A,Lee:3A,Lincoln:3A,Little River:3A,Logan:3A,Lonoke:3A,Madison:4A,Marion:4A,Miller:3A,Mississippi:3A,Monroe:3A,Montgomery:3A,Nevada:3A,Newton:4A,Ouachita:3A,Perry:3A,Phillips:3A,Pike:3A,Poinsett:3A,Polk:3A,Pope:3A,Prairie:3A,Pulaski:3A,Randolph:4A,Saline:3A,Scott:3A,Searcy:4A,Sebastian:3A,Sevier:3A,Sharp:4A,St. Francis:3A,Stone:3A,Union:3A,Van Buren:3A,Washington:4A,White:3A,Woodruff:3A,Yell:3A
CA
Alameda:3C,Alpine:6B,Amador:4B,Butte:3B,Calaveras:4B,Colusa:3B,Contra Costa:3C,Del Norte:4C,El Dorado:4B,Fresno:3B,Glenn:3B,Humboldt:4C,Imperial:2B,Inyo:4B,Kern:3B,Kings:3B,Lake:3C,Lassen:6B,Los Angeles:3B,Madera:3B,Marin:3C,Mariposa:4B,Mendocino:3C,Merced:3B,Modoc:6B,Mono:6B,Monterey:3C,Napa:3C,Nevada:5B,Orange:3B,Placer:4B,Plumas:6B,Riverside:3B,Sacramento:3B,San Benito:3C,San Bernardino:3B,San Diego:3B,San Francisco:3C,San Joaquin:3B,San Luis Obispo:3C,San Mateo:3C,Santa Barbara:3C,Santa Clara:3C,Santa Cruz:3C,Shasta:3B,Sierra:6B,Siskiyou:5B,Solano:3C,Sonoma:3C,Stanislaus:3B,Sutter:3B,Tehama:3B,Trinity:5B,Tulare:3B,Tuolumne:4B,Ventura:3B,Yolo:3B,Yuba:3B
CO
Adams:5B,Alamosa:6B,Arapahoe:5B,Archuleta:6B,Baca:4B,Bent:4B,Boulder:5B,Broomfield:5B,Chaffee:6B,Cheyenne:5B,Clear Creek:6B,Conejos:6B,Costilla:6B,Crowley:4B,Custer:6B,Delta:5B,Denver:5B,Dolores:6B,Douglas:5B,Eagle:6B,El Paso:5B,Elbert:5B,Fremont:5B,Garfield:5B,Gilpin:6B,Grand:6B,Gunnison:7,Hinsdale:7,Huerfano:5B,Jackson:7,Jefferson:5B,Kiowa:4B,Kit Carson:5B,La Plata:5B,Lake:7,Larimer:5B,Las Animas:4B,Lincoln:5B,Logan:5B,Mesa:5B,Mineral:7,Moffat:6B,Montezuma:5B,Montrose:5B,Morgan:5B,Otero:4B,Ouray:6B,Park:6B,Phillips:5B,Pitkin:6B,Prowers:4B,Pueblo:4B,Rio Blanco:6B,Rio Grande:6B,Routt:6B,Saguache:6B,San Juan:7,San Miguel:6B,Sedgwick:5B,Summit:7,Teller:6B,Washington:5B,Weld:5B,Yuma:5B
CT
Fairfield:5A,Hartford:5A,Litchfield:5A,Middlesex:5A,New Haven:5A,New London:5A,Tolland:5A,Windham:5A
DE
Kent:4A,New Castle:4A,Sussex:4A
DC
District of Columbia:4A
FL
Alachua:2A*,Baker:2A*,Bay:2A*,Bradford:2A*,Brevard:2A*,Broward:1A*,Calhoun:2A*,Charlotte:2A*,Citrus:2A*,Clay:2A*,Collier:1A*,Columbia:2A*,DeSoto:2A*,Dixie:2A*,Duval:2A*,Escambia:2A*,Flagler:2A*,Franklin:2A*,Gadsden:2A*,Gilchrist:2A*,Glades:2A*,Gulf:2A*,Hamilton:2A*,Hardee:2A*,Hendry:2A*,Hernando:2A*,Highlands:2A*,Hillsborough:2A*,Holmes:2A*,Indian River:2A*,Jackson:2A*,Jefferson:2A*,Lafayette:2A*,Lake:2A*,Lee:2A*,Leon:2A*,Levy:2A*,Liberty:2A*,Madison:2A*,Manatee:2A*,Marion:2A*,Martin:2A*,Miami-Dade:1A*,Monroe:1A*,Nassau:2A*,Okaloosa:2A*,Okeechobee:2A*,Orange:2A*,Osceola:2A*,Palm Beach:1A*,Pasco:2A*,Pinellas:2A*,Polk:2A*,Putnam:2A*,Santa Rosa:2A*,Sarasota:2A*,Seminole:2A*,St. Johns:2A*,St. Lucie:2A*,Sumter:2A*,Suwannee:2A*,Taylor:2A*,Union:2A*,Volusia:2A*,Wakulla:2A*,Walton:2A*,Washington:2A*
GA
Appling:2A*,Atkinson:2A*,Bacon:2A*,Baker:2A*,Baldwin:3A,Banks:3A,Barrow:3A,Bartow:3A,Ben Hill:2A*,Berrien:2A*,Bibb:3A,Bleckley:3A,Brantley:2A*,Brooks:2A*,Bryan:2A*,Bulloch:2A*,Burke:3A,Butts:3A,Calhoun:2A*,Camden:2A*,Candler:2A*,Carroll:3A,Catoosa:3A,Charlton:2A*,Chatham:2A*,Chattahoochee:2A*,Chattooga:3A,Cherokee:3A,Clarke:3A,Clay:2A*,Clayton:3A,Clinch:2A*,Cobb:3A,Coffee:2A*,Colquitt:2A*,Columbia:3A,Cook:2A*,Coweta:3A,Crawford:3A,Crisp:2A*,Dade:3A,Dawson:3A,Decatur:2A*,DeKalb:3A,Dodge:3A,Dooly:2A*,Dougherty:2A*,Douglas:3A,Early:2A*,Echols:2A*,Effingham:2A*,Elbert:3A,Emanuel:3A,Evans:2A*,Fannin:4A,Fayette:3A,Floyd:3A,Forsyth:3A,Franklin:3A,Fulton:3A,Gilmer:4A,Glascock:3A,Glynn:2A*,Gordon:3A,Grady:2A*,Greene:3A,Gwinnett:3A,Habersham:3A,Hall:3A,Hancock:3A,Haralson:3A,Harris:3A,Hart:3A,Heard:3A,Henry:3A,Houston:3A,Irwin:2A*,Jackson:3A,Jasper:3A,Jeff Davis:2A*,Jefferson:3A,Jenkins:3A,Johnson:3A,Jones:3A,Lamar:3A,Lanier:2A*,Laurens:3A,Lee:2A*,Liberty:2A*,Lincoln:3A,Long:2A*,Lowndes:2A*,Lumpkin:3A,Macon:2A*,Madison:3A,Marion:2A*,McDuffie:3A,McIntosh:2A*,Meriwether:3A,Miller:2A*,Mitchell:2A*,Monroe:3A,Montgomery:2A*,Morgan:3A,Murray:3A,Muscogee:2A*,Newton:3A,Oconee:3A,Oglethorpe:3A,Paulding:3A,Peach:3A,Pickens:3A,Pierce:2A*,Pike:3A,Polk:3A,Pulaski:2A*,Putnam:3A,Quitman:2A*,Rabun:4A,Randolph:2A*,Richmond:3A,Rockdale:3A,Schley:2A*,Screven:3A,Seminole:2A*,Spalding:3A,Stephens:3A,Stewart:2A*,Sumter:2A*,Talbot:3A,Taliaferro:3A,Tattnall:2A*,Taylor:3A*,Telfair:2A*,Terrell:2A*,Thomas:2A*,Tift:2A*,Toombs:2A*,Towns:4A,Treutlen:2A*,Troup:3A,Turner:2A*,Twiggs:3A,Union:4A,Upson:3A,Walker:3A,Walton:3A,Ware:2A*,Warren:3A,Washington:3A,Wayne:2A*,Webster:2A*,Wheeler:2A*,White:3A,Whitfield:3A,Wilcox:2A*,Wilkes:3A,Wilkinson:3A,Worth:2A*
HI
Hawaii:1A*,Honolulu:1A*,Kalawao:1A*,Kauai:1A*,Maui:1A*
ID
Ada:5B,Adams:6B,Bannock:6B,Bear Lake:6B,Benewah:6B,Bingham:6B,Blaine:6B,Boise:6B,Bonner:6B,Bonneville:6B,Boundary:6B,Butte:6B,Camas:6B,Canyon:5B,Caribou:6B,Cassia:5B,Clark:6B,Clearwater:6B,Custer:6B,Elmore:5B,Franklin:6B,Fremont:6B,Gem:5B,Gooding:5B,Idaho:6B,Jefferson:6B,Jerome:5B,Kootenai:6B,Latah:6B,Lemhi:6B,Lewis:6B,Lincoln:5B,Madison:6B,Minidoka:5B,Nez Perce:5B,Oneida:6B,Owyhee:5B,Payette:5B,Power:5B,Shoshone:6B,Teton:6B,Twin Falls:5B,Valley:6B,Washington:5B
IL
Adams:5A,Alexander:4A,Bond:4A,Boone:5A,Brown:5A,Bureau:5A,Calhoun:4A,Carroll:5A,Cass:5A,Champaign:5A,Christian:5A,Clark:4A,Clay:4A,Clinton:4A,Coles:5A,Cook:5A,Crawford:4A,Cumberland:4A,DeKalb:5A,De Witt:5A,Douglas:5A,DuPage:5A,Edgar:5A,Edwards:4A,Effingham:4A,Fayette:4A,Ford:5A,Franklin:4A,Fulton:5A,Gallatin:4A,Greene:4A,Grundy:5A,Hamilton:4A,Hancock:5A,Hardin:4A,Henderson:5A,Henry:5A,Iroquois:5A,Jackson:4A,Jasper:4A,Jefferson:4A,Jersey:4A,Jo Daviess:5A,Johnson:4A,Kane:5A,Kankakee:5A,Kendall:5A,Knox:5A,Lake:5A,LaSalle:5A,Lawrence:4A,Lee:5A,Livingston:5A,Logan:5A,Macon:5A,Macoupin:4A,Madison:4A,Marion:4A,Marshall:5A,Mason:5A,Massac:4A,McDonough:5A,McHenry:5A,McLean:5A,Menard:5A,Mercer:5A,Monroe:4A,Montgomery:4A,Morgan:5A,Moultrie:5A,Ogle:5A,Peoria:5A,Perry:4A,Piatt:5A,Pike:5A,Pope:4A,Pulaski:4A,Putnam:5A,Randolph:4A,Richland:4A,Rock Island:5A,Saline:4A,Sangamon:5A,Schuyler:5A,Scott:5A,Shelby:5A,St. Clair:4A,Stark:5A,Stephenson:5A,Tazewell:5A,Union:4A,Vermilion:5A,Wabash:4A,Warren:5A,Washington:4A,Wayne:4A,White:4A,Whiteside:5A,Will:5A,Williamson:4A,Winnebago:5A,Woodford:5A
IN
Adams:5A,Allen:5A,Bartholomew:4A,Benton:5A,Blackford:5A,Boone:5A,Brown:4A,Carroll:5A,Cass:5A,Clark:4A,Clay:4A,Clinton:5A,Crawford:4A,Daviess:4A,Dearborn:4A,Decatur:4A,DeKalb:5A,Delaware:5A,Dubois:4A,Elkhart:5A,Fayette:4A,Floyd:4A,Fountain:5A,Franklin:4A,Fulton:5A,Gibson:4A,Grant:5A,Greene:4A,Hamilton:5A,Hancock:5A,Harrison:4A,Hendricks:5A,Henry:5A,Howard:5A,Huntington:5A,Jackson:4A,Jasper:5A,Jay:5A,Jefferson:4A,Jennings:4A,Johnson:4A,Knox:4A,Kosciusko:5A,LaGrange:5A,Lake:5A,LaPorte:5A,Lawrence:4A,Madison:5A,Marion:5A,Marshall:5A,Martin:4A,Miami:5A,Monroe:4A,Montgomery:5A,Morgan:4A,Newton:5A,Noble:5A,Ohio:4A,Orange:4A,Owen:4A,Parke:5A,Perry:4A,Pike:4A,Porter:5A,Posey:4A,Pulaski:5A,Putnam:4A,Randolph:5A,Ripley:4A,Rush:4A,Scott:4A,Shelby:4A,Spencer:4A,St. Joseph:5A,Starke:5A,Steuben:5A,Sullivan:4A,Switzerland:4A,Tippecanoe:5A,Tipton:5A,Union:4A,Vanderburgh:4A,Vermillion:5A,Vigo:4A,Wabash:5A,Warren:5A,Warrick:4A,Washington:4A,Wayne:4A,Wells:5A,White:5A,Whitley:5A
IA
Adair:5A,Adams:5A,Allamakee:6A,Appanoose:5A,Audubon:5A,Benton:5A,Black Hawk:5A,Boone:5A,Bremer:6A,Buchanan:5A,Buena Vista:6A,Butler:5A,Calhoun:5A,Carroll:5A,Cass:5A,Cedar:5A,Cerro Gordo:6A,Cherokee:6A,Chickasaw:6A,Clarke:5A,Clay:6A,Clayton:6A,Clinton:5A,Crawford:5A,Dallas:5A,Davis:5A,Decatur:5A,Delaware:5A,Des Moines:5A,Dickinson:6A,Dubuque:5A,Emmet:6A,Fayette:6A,Floyd:6A,Franklin:5A,Fremont:5A,Greene:5A,Grundy:5A,Guthrie:5A,Hamilton:5A,Hancock:6A,Hardin:5A,Harrison:5A,Henry:5A,Howard:6A,Humboldt:6A,Ida:6A,Iowa:5A,Jackson:5A,Jasper:5A,Jefferson:5A,Johnson:5A,Jones:5A,Keokuk:5A,Kossuth:6A,Lee:5A,Linn:5A,Louisa:5A,Lucas:5A,Lyon:6A,Madison:5A,Mahaska:5A,Marion:5A,Marshall:5A,Mills:5A,Mitchell:6A,Monona:5A,Monroe:5A,Montgomery:5A,Muscatine:5A,O'Brien:6A,Osceola:6A,Page:5A,Palo Alto:6A,Plymouth:6A,Pocahontas:6A,Polk:5A,Pottawattamie:5A,Poweshiek:5A,Ringgold:5A,Sac:6A,Scott:5A,Shelby:5A,Sioux:6A,Story:5A,Tama:5A,Taylor:5A,Union:5A,Van Buren:5A,Wapello:5A,Warren:5A,Washington:5A,Wayne:5A,Webster:5A,Winnebago:6A,Winneshiek:6A,Woodbury:5A,Worth:6A,Wright:5A
KS
Allen:4A,Anderson:4A,Atchison:4A,Barber:4A,Barton:4A,Bourbon:4A,Brown:4A,Butler:4A,Chase:4A,Chautauqua:4A,Cherokee:4A,Cheyenne:5A,Clark:4A,Clay:4A,Cloud:4A,Coffey:4A,Comanche:4A,Cowley:4A,Crawford:4A,Decatur:5A,Dickinson:4A,Doniphan:4A,Douglas:4A,Edwards:4A,Elk:4A,Ellis:4A,Ellsworth:4A,Finney:4A,Ford:4A,Franklin:4A,Geary:4A,Gove:4A,Graham:4A,Grant:4A,Gray:4A,Greeley:5A,Greenwood:4A,Hamilton:4A,Harper:4A,Harvey:4A,Haskell:4A,Hodgeman:4A,Jackson:4A,Jefferson:4A,Jewell:4A,Johnson:4A,Kearny:4A,Kingman:4A,Kiowa:4A,Labette:4A,Lane:4A,Leavenworth:4A,Lincoln:4A,Linn:4A,Logan:5A,Lyon:4A,Marion:4A,Marshall:4A,McPherson:4A,Meade:4A,Miami:4A,Mitchell:4A,Montgomery:4A,Morris:4A,Morton:4A,Nemaha:4A,Neosho:4A,Ness:4A,Norton:5A,Osage:4A,Osborne:4A,Ottawa:4A,Pawnee:4A,Phillips:5A,Pottawatomie:4A,Pratt:4A,Rawlins:5A,Reno:4A,Republic:4A,Rice:4A,Riley:4A,Rooks:4A,Rush:4A,Russell:4A,Saline:4A,Scott:4A,Sedgwick:4A,Seward:4A,Shawnee:4A,Sheridan:5A,Sherman:5A,Smith:4A,Stafford:4A,Stanton:4A,Stevens:4A,Sumner:4A,Thomas:5A,Trego:4A,Wabaunsee:4A,Wallace:5A,Washington:4A,Wichita:4A,Wilson:4A,Woodson:4A,Wyandotte:4A
KY
Adair:4A,Allen:4A,Anderson:4A,Ballard:4A,Barren:4A,Bath:4A,Bell:4A,Boone:4A,Bourbon:4A,Boyd:4A,Boyle:4A,Bracken:4A,Breathitt:4A,Breckinridge:4A,Bullitt:4A,Butler:4A,Caldwell:4A,Calloway:4A,Campbell:4A,Carlisle:4A,Carroll:4A,Carter:4A,Casey:4A,Christian:4A,Clark:4A,Clay:4A,Clinton:4A,Crittenden:4A,Cumberland:4A,Daviess:4A,Edmonson:4A,Elliott:4A,Estill:4A,Fayette:4A,Fleming:4A,Floyd:4A,Franklin:4A,Fulton:4A,Gallatin:4A,Garrard:4A,Grant:4A,Graves:4A,Grayson:4A,Green:4A,Greenup:4A,Hancock:4A,Hardin:4A,Harlan:4A,Harrison:4A,Hart:4A,Henderson:4A,Henry:4A,Hickman:4A,Hopkins:4A,Jackson:4A,Jefferson:4A,Jessamine:4A,Johnson:4A,Kenton:4A,Knott:4A,Knox:4A,Larue:4A,Laurel:4A,Lawrence:4A,Lee:4A,Leslie:4A,Letcher:4A,Lewis:4A,Lincoln:4A,Livingston:4A,Logan:4A,Lyon:4A,Madison:4A,Magoffin:4A,Marion:4A,Marshall:4A,Martin:4A,Mason:4A,McCracken:4A,McCreary:4A,McLean:4A,Meade:4A,Menifee:4A,Mercer:4A,Metcalfe:4A,Monroe:4A,Montgomery:4A,Morgan:4A,Muhlenberg:4A,Nelson:4A,Nicholas:4A,Ohio:4A,Oldham:4A,Owen:4A,Owsley:4A,Pendleton:4A,Perry:4A,Pike:4A,Powell:4A,Pulaski:4A,Robertson:4A,Rockcastle:4A,Rowan:4A,Russell:4A,Scott:4A,Shelby:4A,Simpson:4A,Spencer:4A,Taylor:4A,Todd:4A,Trigg:4A,Trimble:4A,Union:4A,Warren:4A,Washington:4A,Wayne:4A,Webster:4A,Whitley:4A,Wolfe:4A,Woodford:4A
LA
Acadia:2A*,Allen:2A*,Ascension:2A*,Assumption:2A*,Avoyelles:2A*,Beauregard:2A*,Bienville:3A,Bossier:3A,Caddo:3A,Calcasieu:2A*,Caldwell:3A,Cameron:2A*,Catahoula:2A*,Claiborne:3A,Concordia:2A*,De Soto:3A,East Baton Rouge:2A*,East Carroll:3A,East Feliciana:2A*,Evangeline:2A*,Franklin:3A,Grant:2A*,Iberia:2A*,Iberville:2A*,Jackson:3A,Jefferson:2A*,Jefferson Davis:2A*,La Salle:2A*,Lafayette:2A*,Lafourche:2A*,Lincoln:3A,Livingston:2A*,Madison:3A,Morehouse:3A,Natchitoches:3A,Orleans:2A*,Ouachita:3A,Plaquemines:2A*,Pointe Coupee:2A*,Rapides:2A*,Red River:3A,Richland:3A,Sabine:3A,St. Bernard:2A*,St. Charles:2A*,St. Helena:2A*,St. James:2A*,St. John the Baptist:2A*,St. Landry:2A*,St. Martin:2A*,St. Mary:2A*,St. Tammany:2A*,Tangipahoa:2A*,Tensas:3A,Terrebonne:2A*,Union:3A,Vermilion:2A*,Vernon:2A*,Washington:2A*,Webster:3A,West Baton Rouge:2A*,West Carroll:3A,West Feliciana:2A*,Winn:3A
ME
Androscoggin:6A,Aroostook:7,Cumberland:6A,Franklin:6A,Hancock:6A,Kennebec:6A,Knox:6A,Lincoln:6A,Oxford:6A,Penobscot:6A,Piscataquis:6A,Sagadahoc:6A,Somerset:6A,Waldo:6A,Washington:6A,York:5A
MD
Allegany:5A,Anne Arundel:4A,Baltimore:4A,Baltimore City:4A,Calvert:4A,Caroline:4A,Carroll:4A,Cecil:4A,Charles:4A,Dorchester:4A,Frederick:4A,Garrett:5A,Harford:4A,Howard:4A,Kent:4A,Montgomery:4A,Prince George's:4A,Queen Anne's:4A,Somerset:4A,St. Mary's:4A,Talbot:4A,Washington:4A,Wicomico:4A,Worcester:4A
MA
Barnstable:5A,Berkshire:5A,Bristol:5A,Dukes:5A,Essex:5A,Franklin:5A,Hampden:5A,Hampshire:5A,Middlesex:5A,Nantucket:5A,Norfolk:5A,Plymouth:5A,Suffolk:5A,Worcester:5A
MI
Alcona:6A,Alger:6A,Allegan:5A,Alpena:6A,Antrim:6A,Arenac:6A,Baraga:6A,Barry:5A,Bay:5A,Benzie:6A,Berrien:5A,Branch:5A,Calhoun:5A,Cass:5A,Charlevoix:6A,Cheboygan:6A,Chippewa:6A,Clare:6A,Clinton:5A,Crawford:6A,Delta:6A,Dickinson:6A,Eaton:5A,Emmet:6A,Genesee:5A,Gladwin:6A,Gogebic:6A,Grand Traverse:6A,Gratiot:5A,Hillsdale:5A,Houghton:6A,Huron:5A,Ingham:5A,Ionia:5A,Iosco:6A,Iron:6A,Isabella:5A,Jackson:5A,Kalamazoo:5A,Kalkaska:6A,Kent:5A,Keweenaw:6A,Lake:6A,Lapeer:5A,Leelanau:6A,Lenawee:5A,Livingston:5A,Luce:6A,Mackinac:6A,Macomb:5A,Manistee:6A,Marquette:6A,Mason:6A,Mecosta:6A,Menominee:6A,Midland:5A,Missaukee:6A,Monroe:5A,Montcalm:5A,Montmorency:6A,Muskegon:5A,Newaygo:6A,Oakland:5A,Oceana:6A,Ogemaw:6A,Ontonagon:6A,Osceola:6A,Oscoda:6A,Otsego:6A,Ottawa:5A,Presque Isle:6A,Roscommon:6A,Saginaw:5A,Sanilac:5A,Schoolcraft:6A,Shiawassee:5A,St. Clair:5A,St. Joseph:5A,Tuscola:5A,Van Buren:5A,Washtenaw:5A,Wayne:5A,Wexford:6A
MN
Aitkin:7,Anoka:6A,Becker:7,Beltrami:7,Benton:6A,Big Stone:6A,Blue Earth:6A,Brown:6A,Carlton:7,Carver:6A,Cass:7,Chippewa:6A,Chisago:6A,Clay:7,Clearwater:7,Cook:7,Cottonwood:6A,Crow Wing:7,Dakota:6A,Dodge:6A,Douglas:6A,Faribault:6A,Fillmore:6A,Freeborn:6A,Goodhue:6A,Grant:7,Hennepin:6A,Houston:6A,Hubbard:7,Isanti:6A,Itasca:7,Jackson:6A,Kanabec:6A,Kandiyohi:6A,Kittson:7,Koochiching:7,Lac qui Parle:6A,Lake:7,Lake of the Woods:7,Le Sueur:6A,Lincoln:6A,Lyon:6A,Mahnomen:7,Marshall:7,Martin:6A,McLeod:6A,Meeker:6A,Mille Lacs:6A,Morrison:7,Mower:6A,Murray:6A,Nicollet:6A,Nobles:6A,Norman:7,Olmsted:6A,Otter Tail:7,Pennington:7,Pine:7,Pipestone:6A,Polk:7,Pope:6A,Ramsey:6A,Red Lake:7,Redwood:6A,Renville:6A,Rice:6A,Rock:6A,Roseau:7,Scott:6A,Sherburne:6A,Sibley:6A,St. Louis:7,Stearns:6A,Steele:6A,Stevens:6A,Swift:6A,Todd:7,Traverse:6A,Wabasha:6A,Wadena:7,Waseca:6A,Washington:6A,Watonwan:6A,Wilkin:7,Winona:6A,Wright:6A,Yellow Medicine:6A
MS
Adams:2A*,Alcorn:3A,Amite:2A*,Attala:3A,Benton:3A,Bolivar:3A,Calhoun:3A,Carroll:3A,Chickasaw:3A,Choctaw:3A,Claiborne:2A*,Clarke:3A,Clay:3A,Coahoma:3A,Copiah:2A*,Covington:2A*,DeSoto:3A,Forrest:2A*,Franklin:2A*,George:2A*,Greene:2A*,Grenada:3A,Hancock:2A*,Harrison:2A*,Hinds:2A*,Holmes:3A,Humphreys:3A,Issaquena:3A,Itawamba:3A,Jackson:2A*,Jasper:3A,Jefferson:2A*,Jefferson Davis:2A*,Jones:2A*,Kemper:3A,Lafayette:3A,Lamar:2A*,Lauderdale:3A,Lawrence:2A*,Leake:3A,Lee:3A,Leflore:3A,Lincoln:2A*,Lowndes:3A,Madison:3A,Marion:2A*,Marshall:3A,Monroe:3A,Montgomery:3A,Neshoba:3A,Newton:3A,Noxubee:3A,Oktibbeha:3A,Panola:3A,Pearl River:2A*,Perry:2A*,Pike:2A*,Pontotoc:3A,Prentiss:3A,Quitman:3A,Rankin:3A,Scott:3A,Sharkey:3A,Simpson:2A*,Smith:3A,Stone:2A*,Sunflower:3A,Tallahatchie:3A,Tate:3A,Tippah:3A,Tishomingo:3A,Tunica:3A,Union:3A,Walthall:2A*,Warren:2A*,Washington:3A,Wayne:2A*,Webster:3A,Wilkinson:2A*,Winston:3A,Yalobusha:3A,Yazoo:3A
MO
Adair:5A,Andrew:5A,Atchison:5A,Audrain:4A,Barry:4A,Barton:4A,Bates:4A,Benton:4A,Bollinger:4A,Boone:4A,Buchanan:4A,Butler:4A,Caldwell:4A,Callaway:4A,Camden:4A,Cape Girardeau:4A,Carroll:4A,Carter:4A,Cass:4A,Cedar:4A,Chariton:5A,Christian:4A,Clark:5A,Clay:4A,Clinton:4A,Cole:4A,Cooper:4A,Crawford:4A,Dade:4A,Dallas:4A,Daviess:5A,DeKalb:5A,Dent:4A,Douglas:4A,Dunklin:3A,Franklin:4A,Gasconade:4A,Gentry:5A,Greene:4A,Grundy:5A,Harrison:5A,Henry:4A,Hickory:4A,Holt:5A,Howard:4A,Howell:4A,Iron:4A,Jackson:4A,Jasper:4A,Jefferson:4A,Johnson:4A,Knox:5A,Laclede:4A,Lafayette:4A,Lawrence:4A,Lewis:5A,Lincoln:4A,Linn:5A,Livingston:5A,Macon:5A,Madison:4A,Maries:4A,Marion:4A,McDonald:4A,Mercer:5A,Miller:4A,Mississippi:4A,Moniteau:4A,Monroe:4A,Montgomery:4A,Morgan:4A,New Madrid:4A,Newton:4A,Nodaway:5A,Oregon:4A,Osage:4A,Ozark:4A,Pemiscot:3A,Perry:4A,Pettis:4A,Phelps:4A,Pike:4A,Platte:4A,Polk:4A,Pulaski:4A,Putnam:5A,Ralls:4A,Randolph:4A,Ray:4A,Reynolds:4A,Ripley:4A,Saline:4A,Schuyler:5A,Scotland:5A,Scott:4A,Shannon:4A,Shelby:4A,St. Charles:4A,St. Clair:4A,St. Francois:4A,St. Louis:4A,St. Louis City:4A,Ste. Genevieve:4A,Stoddard:4A,Stone:4A,Sullivan:5A,Taney:4A,Texas:4A,Vernon:4A,Warren:4A,Washington:4A,Wayne:4A,Webster:4A,Worth:5A,Wright:4A
MT
Beaverhead:6B,Big Horn:6B,Blaine:6B,Broadwater:6B,Carbon:6B,Carter:6B,Cascade:6B,Chouteau:6B,Custer:6B,Daniels:6B,Dawson:6B,Deer Lodge:6B,Fallon:6B,Fergus:6B,Flathead:6B,Gallatin:6B,Garfield:6B,Glacier:6B,Golden Valley:6B,Granite:6B,Hill:6B,Jefferson:6B,Judith Basin:6B,Lake:6B,Lewis and Clark:6B,Liberty:6B,Lincoln:6B,Madison:6B,McCone:6B,Meagher:6B,Mineral:6B,Missoula:6B,Musselshell:6B,Park:6B,Petroleum:6B,Phillips:6B,Pondera:6B,Powder River:6B,Powell:6B,Prairie:6B,Ravalli:6B,Richland:6B,Roosevelt:6B,Rosebud:6B,Sanders:6B,Sheridan:6B,Silver Bow:6B,Stillwater:6B,Sweet Grass:6B,Teton:6B,Toole:6B,Treasure:6B,Valley:6B,Wheatland:6B,Wibaux:6B,Yellowstone:6B
NE
Adams:5A,Antelope:5A,Arthur:5A,Banner:5A,Blaine:5A,Boone:5A,Box Butte:5A,Boyd:5A,Brown:5A,Buffalo:5A,Burt:5A,Butler:5A,Cass:5A,Cedar:5A,Chase:5A,Cherry:5A,Cheyenne:5A,Clay:5A,Colfax:5A,Cuming:5A,Custer:5A,Dakota:5A,Dawes:5A,Dawson:5A,Deuel:5A,Dixon:5A,Dodge:5A,Douglas:5A,Dundy:5A,Fillmore:5A,Franklin:5A,Frontier:5A,Furnas:5A,Gage:5A,Garden:5A,Garfield:5A,Gosper:5A,Grant:5A,Greeley:5A,Hall:5A,Hamilton:5A,Harlan:5A,Hayes:5A,Hitchcock:5A,Holt:5A,Hooker:5A,Howard:5A,Jefferson:5A,Johnson:5A,Kearney:5A,Keith:5A,Keya Paha:5A,Kimball:5A,Knox:5A,Lancaster:5A,Lincoln:5A,Logan:5A,Loup:5A,Madison:5A,McPherson:5A,Merrick:5A,Morrill:5A,Nance:5A,Nemaha:5A,Nuckolls:5A,Otoe:5A,Pawnee:5A,Perkins:5A,Phelps:5A,Pierce:5A,Platte:5A,Polk:5A,Red Willow:5A,Richardson:5A,Rock:5A,Saline:5A,Sarpy:5A,Saunders:5A,Scotts Bluff:5A,Seward:5A,Sheridan:5A,Sherman:5A,Sioux:5A,Stanton:5A,Thayer:5A,Thomas:5A,Thurston:5A,Valley:5A,Washington:5A,Wayne:5A,Webster:5A,Wheeler:5A,York:5A
NV
Carson City:5B,Churchill:5B,Clark:3B,Douglas:5B,Elko:6B,Esmeralda:5B,Eureka:6B,Humboldt:5B,Lander:6B,Lincoln:5B,Lyon:5B,Mineral:5B,Nye:5B,Pershing:5B,Storey:5B,Washoe:5B,White Pine:6B
NH
Belknap:6A,Carroll:6A,Cheshire:6A,Coos:6A,Grafton:6A,Hillsborough:5A,Merrimack:6A,Rockingham:5A,Strafford:6A,Sullivan:6A
NJ
Atlantic:4A,Bergen:4A,Burlington:4A,Camden:4A,Cape May:4A,Cumberland:4A,Essex:4A,Gloucester:4A,Hudson:4A,Hunterdon:4A,Mercer:4A,Middlesex:4A,Monmouth:4A,Morris:5A,Ocean:4A,Passaic:5A,Salem:4A,Somerset:4A,Sussex:5A,Union:4A,Warren:5A
NM
Bernalillo:4B,Catron:5B,Chaves:3B,Cibola:5B,Colfax:5B,Curry:4B,De Baca:4B,Dona Ana:3B,Eddy:3B,Grant:3B,Guadalupe:4B,Harding:4B,Hidalgo:3B,Lea:3B,Lincoln:4B,Los Alamos:5B,Luna:3B,McKinley:5B,Mora:5B,Otero:3B,Quay:4B,Rio Arriba:5B,Roosevelt:4B,San Juan:5B,San Miguel:4B,Sandoval:5B,Santa Fe:5B,Sierra:3B,Socorro:4B,Taos:5B,Torrance:4B,Union:4B,Valencia:4B
NY
Albany:5A,Allegany:6A,Bronx:4A,Broome:6A,Cattaraugus:6A,Cayuga:5A,Chautauqua:5A,Chemung:6A,Chenango:6A,Clinton:6A,Columbia:5A,Cortland:6A,Delaware:6A,Dutchess:5A,Erie:5A,Essex:6A,Franklin:6A,Fulton:6A,Genesee:5A,Greene:5A,Hamilton:6A,Herkimer:6A,Jefferson:6A,Kings:4A,Lewis:6A,Livingston:5A,Madison:6A,Monroe:5A,Montgomery:6A,Nassau:4A,New York:4A,Niagara:5A,Oneida:6A,Onondaga:5A,Ontario:5A,Orange:5A,Orleans:5A,Oswego:5A,Otsego:6A,Putnam:5A,Queens:4A,Rensselaer:5A,Richmond:4A,Rockland:4A,Saratoga:5A,Schenectady:5A,Schoharie:6A,Schuyler:6A,Seneca:5A,St. Lawrence:6A,Steuben:6A,Suffolk:4A,Sullivan:6A,Tioga:6A,Tompkins:6A,Ulster:5A,Warren:6A,Washington:6A,Wayne:5A,Westchester:4A,Wyoming:6A,Yates:5A
NC
Alamance:4A,Alexander:4A,Alleghany:5A,Anson:3A,Ashe:5A,Avery:5A,Beaufort:3A*,Bertie:3A*,Bladen:3A*,Brunswick:3A*,Buncombe:4A,Burke:4A,Cabarrus:3A,Caldwell:4A,Camden:3A*,Carteret:3A*,Caswell:4A,Catawba:3A,Chatham:3A,Cherokee:4A,Chowan:3A*,Clay:4A,Cleveland:3A,Columbus:3A*,Craven:3A*,Cumberland:3A,Currituck:3A*,Dare:3A*,Davidson:3A,Davie:4A,Duplin:3A*,Durham:4A,Edgecombe:3A,Forsyth:4A,Franklin:4A,Gaston:3A,Gates:3A*,Graham:4A,Granville:4A,Greene:3A,Guilford:4A,Halifax:3A,Harnett:3A,Haywood:4A,Henderson:4A,Hertford:3A*,Hoke:3A,Hyde:3A*,Iredell:3A,Jackson:4A,Johnston:3A,Jones:3A*,Lee:3A,Lenoir:3A,Lincoln:3A,Macon:4A,Madison:4A,Martin:3A*,McDowell:4A,Mecklenburg:3A,Mitchell:5A,Montgomery:3A,Moore:3A,Nash:3A,New Hanover:3A*,Northampton:3A,Onslow:3A*,Orange:4A,Pamlico:3A*,Pasquotank:3A*,Pender:3A*,Perquimans:3A*,Person:4A,Pitt:3A,Polk:4A,Randolph:3A,Richmond:3A,Robeson:3A*,Rockingham:4A,Rowan:3A,Rutherford:3A,Sampson:3A,Scotland:3A,Stanly:3A,Stokes:4A,Surry:4A,Swain:4A,Transylvania:4A,Tyrrell:3A*,Union:3A,Vance:4A,Wake:4A,Warren:4A,Washington:3A*,Watauga:5A,Wayne:3A,Wilkes:4A,Wilson:3A,Yadkin:4A,Yancey:5A
ND
Adams:6A,Barnes:6A,Benson:7,Billings:6A,Bottineau:7,Bowman:6A,Burke:7,Burleigh:6A,Cass:6A,Cavalier:7,Dickey:6A,Divide:7,Dunn:6A,Eddy:7,Emmons:6A,Foster:7,Golden Valley:6A,Grand Forks:7,Grant:6A,Griggs:7,Hettinger:6A,Kidder:6A,LaMoure:6A,Logan:6A,McHenry:7,McIntosh:6A,McKenzie:6A,McLean:7,Mercer:6A,Morton:6A,Mountrail:7,Nelson:7,Oliver:6A,Pembina:7,Pierce:7,Ramsey:7,Ransom:6A,Renville:7,Richland:6A,Rolette:7,Sargent:6A,Sheridan:7,Sioux:6A,Slope:6A,Stark:6A,Steele:7,Stutsman:6A,Towner:7,Traill:7,Walsh:7,Ward:7,Wells:7,Williams:6A
OH
Adams:4A,Allen:5A,Ashland:5A,Ashtabula:5A,Athens:4A,Auglaize:5A,Belmont:5A,Brown:4A,Butler:4A,Carroll:5A,Champaign:5A,Clark:5A,Clermont:4A,Clinton:4A,Columbiana:5A,Coshocton:5A,Crawford:5A,Cuyahoga:5A,Darke:5A,Defiance:5A,Delaware:5A,Erie:5A,Fairfield:4A,Fayette:4A,Franklin:5A,Fulton:5A,Gallia:4A,Geauga:5A,Greene:4A,Guernsey:5A,Hamilton:4A,Hancock:5A,Hardin:5A,Harrison:5A,Henry:5A,Highland:4A,Hocking:4A,Holmes:5A,Huron:5A,Jackson:4A,Jefferson:5A,Knox:5A,Lake:5A,Lawrence:4A,Licking:5A,Logan:5A,Lorain:5A,Lucas:5A,Madison:5A,Mahoning:5A,Marion:5A,Medina:5A,Meigs:4A,Mercer:5A,Miami:5A,Monroe:4A,Montgomery:4A,Morgan:4A,Morrow:5A,Muskingum:5A,Noble:4A,Ottawa:5A,Paulding:5A,Perry:4A,Pickaway:4A,Pike:4A,Portage:5A,Preble:4A,Putnam:5A,Richland:5A,Ross:4A,Sandusky:5A,Scioto:4A,Seneca:5A,Shelby:5A,Stark:5A,Summit:5A,Trumbull:5A,Tuscarawas:5A,Union:5A,Van Wert:5A,Vinton:4A,Warren:4A,Washington:4A,Wayne:5A,Williams:5A,Wood:5A,Wyandot:5A
OK
Adair:3A,Alfalfa:4A,Atoka:3A,Beaver:4A,Beckham:3A,Blaine:3A,Bryan:3A,Caddo:3A,Canadian:3A,Carter:3A,Cherokee:3A,Choctaw:3A,Cimarron:4B,Cleveland:3A,Coal:3A,Comanche:3A,Cotton:3A,Craig:4A,Creek:3A,Custer:3A,Delaware:4A,Dewey:3A,Ellis:4A,Garfield:3A,Garvin:3A,Grady:3A,Grant:4A,Greer:3A,Harmon:3A,Harper:4A,Haskell:3A,Hughes:3A,Jackson:3A,Jefferson:3A,Johnston:3A,Kay:4A,Kingfisher:3A,Kiowa:3A,Latimer:3A,Le Flore:3A,Lincoln:3A,Logan:3A,Love:3A,Major:3A,Marshall:3A,Mayes:3A,McClain:3A,McCurtain:3A,McIntosh:3A,Murray:3A,Muskogee:3A,Noble:3A,Nowata:3A,Okfuskee:3A,Oklahoma:3A,Okmulgee:3A,Osage:3A,Ottawa:4A,Pawnee:3A,Payne:3A,Pittsburg:3A,Pontotoc:3A,Pottawatomie:3A,Pushmataha:3A,Roger Mills:3A,Rogers:3A,Seminole:3A,Sequoyah:3A,Stephens:3A,Texas:4A,Tillman:3A,Tulsa:3A,Wagoner:3A,Washington:3A,Washita:3A,Woods:4A,Woodward:4A
OR
Baker:5B,Benton:4C,Clackamas:4C,Clatsop:4C,Columbia:4C,Coos:4C,Crook:5B,Curry:4C,Deschutes:5B,Douglas:4C,Gilliam:5B,Grant:6B,Harney:5B,Hood River:5B,Jackson:4C,Jefferson:5B,Josephine:4C,Klamath:5B,Lake:5B,Lane:4C,Lincoln:4C,Linn:4C,Malheur:5B,Marion:4C,Morrow:5B,Multnomah:4C,Polk:4C,Sherman:5B,Tillamook:4C,Umatilla:5B,Union:6B,Wallowa:6B,Wasco:5B,Washington:4C,Wheeler:5B,Yamhill:4C
PA
Adams:5A,Allegheny:5A,Armstrong:5A,Beaver:5A,Bedford:5A,Berks:5A,Blair:5A,Bradford:6A,Bucks:4A,Butler:5A,Cambria:5A,Cameron:6A,Carbon:5A,Centre:5A,Chester:4A,Clarion:5A,Clearfield:5A,Clinton:5A,Columbia:5A,Crawford:5A,Cumberland:5A,Dauphin:5A,Delaware:4A,Elk:6A,Erie:5A,Fayette:5A,Forest:6A,Franklin:5A,Fulton:5A,Greene:4A,Huntingdon:5A,Indiana:5A,Jefferson:5A,Juniata:5A,Lackawanna:5A,Lancaster:4A,Lawrence:5A,Lebanon:5A,Lehigh:5A,Luzerne:5A,Lycoming:5A,McKean:6A,Mercer:5A,Mifflin:5A,Monroe:5A,Montgomery:4A,Montour:5A,Northampton:5A,Northumberland:5A,Perry:5A,Philadelphia:4A,Pike:6A,Potter:6A,Schuylkill:5A,Snyder:5A,Somerset:5A,Sullivan:6A,Susquehanna:6A,Tioga:6A,Union:5A,Venango:5A,Warren:6A,Washington:5A,Wayne:6A,Westmoreland:5A,Wyoming:6A,York:4A
RI
Bristol:5A,Kent:5A,Newport:5A,Providence:5A,Washington:5A
SC
Abbeville:3A,Aiken:3A,Allendale:2A*,Anderson:3A,Bamberg:3A*,Barnwell:3A*,Beaufort:2A*,Berkeley:3A*,Calhoun:3A,Charleston:2A*,Cherokee:3A,Chester:3A,Chesterfield:3A,Clarendon:3A*,Colleton:2A*,Darlington:3A,Dillon:3A*,Dorchester:2A*,Edgefield:3A,Fairfield:3A,Florence:3A,Georgetown:2A*,Greenville:3A,Greenwood:3A,Hampton:2A*,Horry:2A*,Jasper:2A*,Kershaw:3A,Lancaster:3A,Laurens:3A,Lee:3A,Lexington:3A,Marion:3A*,Marlboro:3A,McCormick:3A,Newberry:3A,Oconee:3A,Orangeburg:3A,Pickens:3A,Richland:3A,Saluda:3A,Spartanburg:3A,Sumter:3A,Union:3A,Williamsburg:3A*,York:3A
SD
Aurora:6A,Beadle:6A,Bennett:5A,Bon Homme:5A,Brookings:6A,Brown:6A,Brule:5A,Buffalo:6A,Butte:5B,Campbell:6A,Charles Mix:5A,Clark:6A,Clay:5A,Codington:6A,Corson:6A,Custer:5B,Davison:5A,Day:6A,Deuel:6A,Dewey:6A,Douglas:5A,Edmunds:6A,Fall River:5B,Faulk:6A,Grant:6A,Gregory:5A,Haakon:5B,Hamlin:6A,Hand:6A,Hanson:5A,Harding:6B,Hughes:5A,Hutchinson:5A,Hyde:6A,Jackson:5B,Jerauld:6A,Jones:5A,Kingsbury:6A,Lake:6A,Lawrence:6B,Lincoln:5A,Lyman:5A,Marshall:6A,McCook:5A,McPherson:6A,Meade:5B,Mellette:5A,Miner:6A,Minnehaha:6A,Moody:6A,Pennington:5B,Perkins:6A,Potter:6A,Roberts:6A,Sanborn:6A,Shannon:5B,Spink:6A,Stanley:5A,Sully:6A,Todd:5A,Tripp:5A,Turner:5A,Union:5A,Walworth:6A,Yankton:5A,Ziebach:6A
TN
Anderson:4A,Bedford:4A,Benton:4A,Bledsoe:4A,Blount:4A,Bradley:4A,Campbell:4A,Cannon:4A,Carroll:4A,Carter:4A,Cheatham:4A,Chester:3A,Claiborne:4A,Clay:4A,Cocke:4A,Coffee:4A,Crockett:3A,Cumberland:4A,Davidson:4A,Decatur:4A,DeKalb:4A,Dickson:4A,Dyer:3A,Fayette:3A,Fentress:4A,Franklin:4A,Gibson:3A,Giles:4A,Grainger:4A,Greene:4A,Grundy:4A,Hamblen:4A,Hamilton:4A,Hancock:4A,Hardeman:3A,Hardin:3A,Hawkins:4A,Haywood:3A,Henderson:4A,Henry:4A,Hickman:4A,Houston:4A,Humphreys:4A,Jackson:4A,Jefferson:4A,Johnson:4A,Knox:4A,Lake:4A,Lauderdale:3A,Lawrence:4A,Lewis:4A,Lincoln:4A,Loudon:4A,Macon:4A,Madison:3A,Marion:4A,Marshall:4A,Maury:4A,McMinn:4A,McNairy:3A,Meigs:4A,Monroe:4A,Montgomery:4A,Moore:4A,Morgan:4A,Obion:4A,Overton:4A,Perry:4A,Pickett:4A,Polk:4A,Putnam:4A,Rhea:4A,Roane:4A,Robertson:4A,Rutherford:4A,Scott:4A,Sequatchie:4A,Sevier:4A,Shelby:3A,Smith:4A,Stewart:4A,Sullivan:4A,Sumner:4A,Tipton:3A,Trousdale:4A,Unicoi:4A,Union:4A,Van Buren:4A,Warren:4A,Washington:4A,Wayne:4A,Weakley:4A,White:4A,Williamson:4A,Wilson:4A
TX
Anderson:3A,Andrews:3B,Angelina:2A*,Aransas:2A*,Archer:3A,Armstrong:4B,Atascosa:2A,Austin:2A*,Bailey:4B,Bandera:2A,Bastrop:2A,Baylor:3A,Bee:2A*,Bell:2A,Bexar:2A,Blanco:3A,Borden:3B,Bosque:3A,Bowie:3A,Brazoria:2A*,Brazos:2A,Brewster:3B,Briscoe:4B,Brooks:2A*,Brown:3A,Burleson:2A,Burnet:3A,Caldwell:2A,Calhoun:2A*,Callahan:3A,Cameron:2A*,Camp:3A,Carson:4B,Cass:3A,Castro:4B,Chambers:2A*,Cherokee:3A,Childress:3A,Clay:3A,Cochran:3B,Coke:3B,Coleman:3A,Collin:3A,Collingsworth:3A,Colorado:2A*,Comal:2A,Comanche:3A,Concho:3B,Cooke:3A,Coryell:2A,Cottle:3A,Crane:3B,Crockett:3B,Crosby:3B,Culberson:3B,Dallam:4B,Dallas:3A,Dawson:3B,Deaf Smith:4B,Delta:3A,Denton:3A,DeWitt:2A*,Dickens:3A,Dimmit:2B,Donley:3A,Duval:2A*,Eastland:3A,Ector:3B,Edwards:2B,El Paso:3B,Ellis:3A,Erath:3A,Falls:2A,Fannin:3A,Fayette:2A,Fisher:3A,Floyd:3B,Foard:3A,Fort Bend:2A*,Franklin:3A,Freestone:3A,Frio:2A,Gaines:3B,Galveston:2A*,Garza:3B,Gillespie:3A,Glasscock:3B,Goliad:2A*,Gonzales:2A,Gray:4B,Grayson:3A,Gregg:3A,Grimes:2A,Guadalupe:2A,Hale:3B,Hall:3A,Hamilton:3A,Hansford:4B,Hardeman:3A,Hardin:2A*,Harris:2A*,Harrison:3A,Hartley:4B,Haskell:3A,Hays:2A,Hemphill:4A,Henderson:3A,Hidalgo:2A*,Hill:3A,Hockley:3B,Hood:3A,Hopkins:3A,Houston:2A*,Howard:3B,Hudspeth:3B,Hunt:3A,Hutchinson:4B,Irion:3B,Jack:3A,Jackson:2A*,Jasper:2A*,Jeff Davis:3B,Jefferson:2A*,Jim Hogg:2A*,Jim Wells:2A*,Johnson:3A,Jones:3A,Karnes:2A,Kaufman:3A,Kendall:2A,Kenedy:2A*,Kent:3A,Kerr:2A,Kimble:3B,King:3A,Kinney:2B,Kleberg:2A*,Knox:3A,La Salle:2A,Lamar:3A,Lamb:3B,Lampasas:2A,Lavaca:2A,Lee:2A,Leon:2A,Liberty:2A*,Limestone:2A,Lipscomb:4A,Live Oak:2A*,Llano:2A,Loving:3B,Lubbock:3B,Lynn:3B,Madison:2A,Marion:3A,Martin:3B,Mason:3B,Matagorda:2A*,Maverick:2B,McCulloch:3B,McLennan:2A,McMullen:2A,Medina:2A,Menard:3B,Midland:3B,Milam:2A,Mills:3A,Mitchell:3A,Montague:3A,Montgomery:2A*,Moore:4B,Morris:3A,Motley:3A,Nacogdoches:3A,Navarro:3A,Newton:2A*,Nolan:3A,Nueces:2A*,Ochiltree:4A,Oldham:4B,Orange:2A*,Palo Pinto:3A,Panola:3A,Parker:3A,Parmer:4B,Pecos:3B,Polk:2A*,Potter:4B,Presidio:3B,Rains:3A,Randall:4B,Reagan:3B,Real:2A,Red River:3A,Reeves:3B,Refugio:2A*,Roberts:4B,Robertson:2A,Rockwall:3A,Runnels:3A,Rusk:3A,Sabine:3A,San Augustine:3A,San Jacinto:2A*,San Patricio:2A*,San Saba:3A,Schleicher:3B,Scurry:3A,Shackelford:3A,Shelby:3A,Sherman:4B,Smith:3A,Somervell:3A,Starr:2A*,Stephens:3A,Sterling:3B,Stonewall:3A,Sutton:3B,Swisher:4B,Tarrant:3A,Taylor:3A,Terrell:3B,Terry:3B,Throckmorton:3A,Titus:3A,Tom Green:3B,Travis:2A,Trinity:2A*,Tyler:2A*,Upshur:3A,Upton:3B,Uvalde:2B,Val Verde:2B,Van Zandt:3A,Victoria:2A*,Walker:2A*,Waller:2A*,Ward:3B,Washington:2A,Webb:2A,Wharton:2A*,Wheeler:4A,Wichita:3A,Wilbarger:3A,Willacy:2A*,Williamson:2A,Wilson:2A,Winkler:3B,Wise:3A,Wood:3A,Yoakum:3B,Young:3A,Zapata:2A,Zavala:2B
UT
Beaver:5B,Box Elder:5B,Cache:6B,Carbon:5B,Daggett:6B,Davis:5B,Duchesne:6B,Emery:5B,Garfield:5B,Grand:5B,Iron:5B,Juab:5B,Kane:5B,Millard:5B,Morgan:6B,Piute:6B,Rich:6B,Salt Lake:5B,San Juan:5B,Sanpete:6B,Sevier:5B,Summit:6B,Tooele:5B,Uintah:5B,Utah:5B,Wasatch:6B,Washington:3B,Wayne:5B,Weber:5B
VT
Addison:6A,Bennington:6A,Caledonia:6A,Chittenden:6A,Essex:6A,Franklin:6A,Grand Isle:6A,Lamoille:6A,Orange:6A,Orleans:6A,Rutland:6A,Washington:6A,Windham:6A,Windsor:6A
VA
Accomack:4A,Albemarle:4A,Alexandria:4A,Alleghany:4A,Amelia:4A,Amherst:4A,Appomattox:4A,Arlington:4A,Augusta:4A,Bath:4A,Bedford:4A,Bland:4A,Botetourt:4A,Bristol:4A,Brunswick:4A,Buchanan:4A,Buckingham:4A,Buena Vista:4A,Campbell:4A,Caroline:4A,Carroll:4A,Charles City:4A,Charlotte:4A,Charlottesville:4A,Chesapeake:4A,Chesterfield:4A,Clarke:4A,Colonial Heights:4A,Covington:4A,Craig:4A,Culpeper:4A,Cumberland:4A,Danville:4A,Dickenson:4A,Dinwiddie:4A,Emporia:4A,Essex:4A,Fairfax:4A,Fairfax City:4A,Falls Church:4A,Fauquier:4A,Floyd:4A,Fluvanna:4A,Franklin:4A,Franklin City:4A,Frederick:4A,Fredericksburg:4A,Galax:4A,Giles:4A,Gloucester:4A,Goochland:4A,Grayson:4A,Greene:4A,Greensville:4A,Halifax:4A,Hampton:4A,Hanover:4A,Harrisonburg:4A,Henrico:4A,Henry:4A,Highland:5A,Hopewell:4A,Isle of Wight:4A,James City:4A,King and Queen:4A,King George:4A,King William:4A,Lancaster:4A,Lee:4A,Lexington:4A,Loudoun:4A,Louisa:4A,Lunenburg:4A,Lynchburg:4A,Madison:4A,Manassas:4A,Manassas Park:4A,Martinsville:4A,Mathews:4A,Mecklenburg:4A,Middlesex:4A,Montgomery:4A,Nelson:4A,New Kent:4A,Newport News:4A,Norfolk:4A,Northampton:4A,Northumberland:4A,Norton:4A,Nottoway:4A,Orange:4A,Page:4A,Patrick:4A,Petersburg:4A,Pittsylvania:4A,Poquoson:4A,Portsmouth:4A,Powhatan:4A,Prince Edward:4A,Prince George:4A,Prince William:4A,Pulaski:4A,Radford:4A,Rappahannock:4A,Richmond:4A,Richmond City:4A,Roanoke:4A,Roanoke City:4A,Rockbridge:4A,Rockingham:4A,Russell:4A,Salem:4A,Scott:4A,Shenandoah:4A,Smyth:4A,Southampton:4A,Spotsylvania:4A,Stafford:4A,Staunton:4A,Suffolk:4A,Surry:4A,Sussex:4A,Tazewell:4A,Virginia Beach:4A,Warren:4A,Washington:4A,Waynesboro:4A,Westmoreland:4A,Williamsburg:4A,Winchester:4A,Wise:4A,Wythe:4A,York:4A
WA
Adams:5B,Asotin:5B,Benton:5B,Chelan:5B,Clallam:4C,Clark:4C,Columbia:5B,Cowlitz:4C,Douglas:5B,Ferry:6B,Franklin:5B,Garfield:5B,Grant:5B,Grays Harbor:4C,Island:4C,Jefferson:4C,King:4C,Kitsap:4C,Kittitas:5B,Klickitat:5B,Lewis:4C,Lincoln:5B,Mason:4C,Okanogan:6B,Pacific:4C,Pend Oreille:6B,Pierce:4C,San Juan:4C,Skagit:4C,Skamania:4C,Snohomish:4C,Spokane:5B,Stevens:6B,Thurston:4C,Wahkiakum:4C,Walla Walla:5B,Whatcom:4C,Whitman:5B,Yakima:5B
WV
Barbour:5A,Berkeley:4A,Boone:4A,Braxton:4A,Brooke:5A,Cabell:4A,Calhoun:4A,Clay:4A,Doddridge:4A,Fayette:4A,Gilmer:4A,Grant:5A,Greenbrier:4A,Hampshire:4A,Hancock:5A,Hardy:4A,Harrison:5A,Jackson:4A,Jefferson:4A,Kanawha:4A,Lewis:4A,Lincoln:4A,Logan:4A,Marion:5A,Marshall:5A,Mason:4A,McDowell:4A,Mercer:4A,Mineral:4A,Mingo:4A,Monongalia:5A,Monroe:4A,Morgan:4A,Nicholas:4A,Ohio:5A,Pendleton:5A,Pleasants:4A,Pocahontas:5A,Preston:5A,Putnam:4A,Raleigh:4A,Randolph:5A,Ritchie:4A,Roane:4A,Summers:4A,Taylor:5A,Tucker:5A,Tyler:4A,Upshur:5A,Wayne:4A,Webster:4A,Wetzel:5A,Wirt:4A,Wood:4A,Wyoming:4A
WI
Adams:6A,Ashland:7,Barron:6A,Bayfield:7,Brown:6A,Buffalo:6A,Burnett:7,Calumet:6A,Chippewa:6A,Clark:6A,Columbia:6A,Crawford:6A,Dane:6A,Dodge:6A,Door:6A,Douglas:7,Dunn:6A,Eau Claire:6A,Florence:7,Fond du Lac:6A,Forest:7,Grant:5A,Green:6A,Green Lake:6A,Iowa:6A,Iron:7,Jackson:6A,Jefferson:6A,Juneau:6A,Kenosha:5A,Kewaunee:6A,La Crosse:6A,Lafayette:5A,Langlade:7,Lincoln:7,Manitowoc:6A,Marathon:6A,Marinette:6A,Marquette:6A,Menominee:6A,Milwaukee:6A,Monroe:6A,Oconto:6A,Oneida:7,Outagamie:6A,Ozaukee:6A,Pepin:6A,Pierce:6A,Polk:6A,Portage:6A,Price:7,Racine:6A,Richland:6A,Rock:6A,Rusk:6A,Sauk:6A,Sawyer:7,Shawano:6A,Sheboygan:6A,St. Croix:6A,Taylor:7,Trempealeau:6A,Vernon:6A,Vilas:7,Walworth:6A,Washburn:7,Washington:6A,Waukesha:6A,Waupaca:6A,Waushara:6A,Winnebago:6A,Wood:6A
WY
Albany:6B,Big Horn:6B,Campbell:6B,Carbon:6B,Converse:6B,Crook:6B,Fremont:6B,Goshen:5B,Hot Springs:6B,Johnson:6B,Laramie:5B,Lincoln:7,Natrona:6B,Niobrara:6B,Park:6B,Platte:5B,Sheridan:6B,Sublette:7,Sweetwater:6B,Teton:7,Uinta:6B,Washakie:6B,Weston:6B
AS
All:1A*
GU
All:1A*
MP
All:1A*
PR
All:1A*
VI
All:1A*
`;
